### ISSUE TITLE
Upgrade dependencies to elm-community/elm-test 2.0.0

### ISSUE THREAD

**Issue by rtfeldman** [elm-community/html-test-runner#1]
Also ought to put a README together.

**Comment by mgold** [comment]
Shouldn't elm-community own this? I thought we learned our lesson with repos spread across NRI and deadfoxygrandpa.

**Comment by rtfeldman** [comment]
I talked with Noah about that and he basically suggested I default to
putting things in private repos if I intended to maintain them myself.

That seems in line with
https://github.com/elm-community/Manifesto/blob/master/README.md - which
says elm-community is more where we should move packages that need
maintenance work after initial maintainers are no longer up for it.

It says "innovative work" should continue to happen in private repos, and I
definitely intend to continue actively improving both this runner and the
node runner!

**Comment by rtfeldman** [comment]
This is done.
