### ISSUE TITLE
Styling [HELP WANTED]

### ISSUE THREAD

**Issue by kofigumbs** [elm-community/html-test-runner#5]
Currently, the test runner is low on frills. Since the test runner can be someone's earliest experience with the language, it would be great to make it look and feel nice! I'm not trained in UI/UX, but I would love to work with anyone interested in tackling this (especially beginners)!

Reach out if your interested, and we can talk through ideas!

**Comment by gregziegan** [comment]
Hey! Wanna pair/chat sometime? It'd be cool to make this really nice 🙂 

I do a lot of front-end work, but I'd like to try my hand at design. I can add code or just sketch files and make issues

**Comment by mgold** [comment]
Just a passing thought, could it be made to look like elm-reactor?

**Comment by kofigumbs** [comment]
@thebritican that's awesome. @mgold's elm-reactor idea seems good to me. If you wanna pair on bringing that in, let's touch base on Slack (@ kofi)—otherwise, feel free to submit a PR and we can continue the conversation there.
