### ISSUE TITLE
Forced downgrade of mdgriffith/style-elements

### ISSUE THREAD

**Issue by trippingtarballs** [elm-community/html-test-runner#8]
The issue comes up when I go to add `elm-community/html-test-runner` to my project. 

```sh
$ elm-package install elm-community/html-test-runner


To install elm-community/html-test-runner I would like to add the following
dependency to elm-package.json:

    "elm-community/html-test-runner": "1.0.6 <= v < 2.0.0"

May I add that to elm-package.json for you? [Y/n] Y

Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-community/html-test-runner 1.0.6
  Upgrade:
    mdgriffith/style-elements (4.2.1 => 3.4.1)

Do you approve of this plan? [Y/n]
```

I don't know what's going on here ... It would seem to be that the dependency resolution of `elm-package` wants to **downgrade my `mdgriffith/style-elements` package**.

This is what I have in the dependencies of my project's `elm-package.json` (before I attempt the install command):

```json
    "dependencies": {
        "NoRedInk/elm-decode-pipeline": "3.0.0 <= v < 4.0.0",
        "danyx23/elm-dropzone": "2.0.1 <= v < 3.0.0",
        "danyx23/elm-mimetype": "3.0.2 <= v < 4.0.0",
        "eeue56/elm-html-test": "5.1.2 <= v < 6.0.0",
        "elm-community/elm-test": "4.1.0 <= v < 5.0.0",
        "elm-community/json-extra": "2.5.0 <= v < 3.0.0",
        "elm-community/list-extra": "7.0.1 <= v < 8.0.0",
        "elm-lang/core": "5.1.1 <= v < 6.0.0",
        "elm-lang/dom": "1.1.1 <= v < 2.0.0",
        "elm-lang/html": "2.0.0 <= v < 3.0.0",
        "elm-lang/http": "1.0.0 <= v < 2.0.0",
        "elm-lang/navigation": "2.1.0 <= v < 3.0.0",
        "evancz/elm-markdown": "3.0.2 <= v < 4.0.0",
        "evancz/url-parser": "2.0.1 <= v < 3.0.0",
        "justinmimbs/elm-date-extra": "2.0.3 <= v < 3.0.0",
        "krisajenkins/elm-exts": "27.4.0 <= v < 28.0.0",
        "lukewestby/elm-http-builder": "5.1.0 <= v < 6.0.0",
        "mdgriffith/style-elements": "4.2.1 <= v < 5.0.0",
        "mgold/elm-date-format": "1.3.0 <= v < 2.0.0",
        "mgold/elm-random-pcg": "4.0.2 <= v < 5.0.0",
        "ohanhi/keyboard-extra": "3.0.4 <= v < 4.0.0",
        "rtfeldman/elm-validate": "1.1.3 <= v < 2.0.0",
        "rtfeldman/selectlist": "1.0.0 <= v < 2.0.0"
    },
```

I notice there was a change to your `elm-community/html-test-runner`'s use of `mdgriffith/style-elements` in the [last release](https://github.com/elm-community/html-test-runner/compare/1.0.6...master#diff-acb0d17193d51673902f9923e878d4f4R16). But that was some time ago. I can only assume that I'm doing something stupid on my side. 😢

**Comment by trippingtarballs** [comment]
It would seem that there is a [know issue](https://github.com/elm-lang/elm-package/issues/279) in `elm-package` that might explain why I'm seeing this:

> _"If a downstream package specifies a maximum version while `elm-package.json` specifies a version above that, the maximum downstream version will be selected rather than the explicitly set one."_

The reason I say that this known issue _might_ explain my reported issue is because I already have `mdgriffith/style-elements` installed at a version the downstream package specifies. I'm so confused! 🤯

**Comment by halcwb** [comment]
Same problem here, cannot use this because I am using a more recent version of style-elements. 

By the way, elm-package says upgrade SE (4.2.1 => 3.4.1) ?? That's a downgrade, not an upgrade.

**Comment by kofigumbs** [comment]
@trippingtarballs my apologies for the late response!! Seems I accidentally disabled email notifications somewhere along the way. [1.0.7](https://github.com/elm-community/html-test-runner/releases/tag/1.0.7) should fix your issue, but please let me know if it doesn't.

The problem was that I hadn't published the version even though I pushed the update to `master` 😅 . Thanks for raising the flag!
